spring:
  resources.static-locations: classpath:/META-INF/resources/,classpath:/html/,classpath:/resources/,classpath:/static/,classpath:/public/
  # #################################### MySQL链接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xbd?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT
    username: root
    password: root


server:
  port: 80
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css,text/javascript

logging:
  level:
    com.example.mybatis.mapper: info